#!/usr/bin/env python
import django, sys
from django.conf import settings

settings.configure(
    DEBUG=True,
    DATABASES={
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    },
    ROOT_URLCONF='events.urls',
    INSTALLED_APPS=(
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'events',
        'django_nose'
    ),

    # TEST_RUNNER = 'django_nose.NoseTestSuiteRunner',
    # NOSE_ARGS = [
    #     '--with-coverage',
    #     '--cover-package=events',
    # ]
)

django.setup()
from django.test.runner import DiscoverRunner
test_runner = DiscoverRunner(verbosity=1)

args = ['events.tests', ]
if len(sys.argv) > 1:
    args = sys.argv[1:]

failures = test_runner.run_tests(args)
if failures:
    sys.exit(failures)